import test from "node:test";
import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";

const migrationDirectory = new URL("../db/migrations/", import.meta.url);

test("target migrations are ordered from Better Auth identity to application tables", async () => {
  const files = (await readdir(migrationDirectory)).sort();
  assert.deepEqual(files, ["001_better_auth_1_7_1.generated.sql", "002_app_baseline.sql", "003_add_company_position.sql", "004_ai_usage_cycle_anchor.sql", "005_user_legal_acceptances.sql"]);
});

test("generated Better Auth 1.7.1 schema contains only configured core models", async () => {
  const sql = await readFile(new URL("001_better_auth_1_7_1.generated.sql", migrationDirectory), "utf8");
  assert.match(sql, /Generated by auth@1\.7\.1/);
  assert.match(sql, /create schema if not exists auth/);
  for (const table of ["user", "session", "account", "verification"]) {
    assert.match(sql, new RegExp(`create table "${table}"`));
  }
  assert.equal((sql.match(/create table/g) || []).length, 4);
  assert.match(sql, /"id" uuid default pg_catalog\.gen_random_uuid\(\)/);
  assert.match(sql, /account_issuer_accountId_uidx/);
});

test("application baseline preserves Stage 0 schema invariants", async () => {
  const sql = await readFile(new URL("002_app_baseline.sql", migrationDirectory), "utf8");
  const tables = [
    "users", "projects", "performers", "quick_access_items", "template_libraries",
    "ai_settings", "studio_export_profiles", "export_presets", "ai_usage_events",
    "product_events", "user_flags", "ai_usage_limits", "ai_usage_reservations", "beta_feedback",
  ];
  for (const table of tables) assert.match(sql, new RegExp(`create table public\\.${table} \\(`));
  assert.doesNotMatch(sql, /public\.profiles|auth\.users|storage\.|enable row level security|create policy/i);
  assert.match(sql, /auth_user_id uuid not null unique/);
  assert.match(sql, /foreign key \(auth_user_id\) references auth\."user" \(id\) on delete cascade/);
  assert.equal((sql.match(/references public\.users \(id\)/g) || []).length, 13);
  assert.match(sql, /foreign key \(user_id, performer_client_id\)[\s\S]*references public\.performers \(user_id, client_id\) on delete cascade/);
  for (const trigger of [
    "ai_settings", "ai_usage_limits", "performers", "projects",
    "quick_access_items", "template_libraries", "user_flags",
  ]) assert.match(sql, new RegExp(`create trigger ${trigger}_set_updated_at`));
  assert.equal((sql.match(/create trigger/g) || []).length, 7);
  assert.match(sql, /octet_length\(personalization\) <= 12000/);
  assert.match(sql, /jsonb_typeof\(preset_json\) = 'object'/);
  assert.match(sql, /quick_access_items_user_sort_idx/);
  assert.match(sql, /projects_updated_at_idx/);
});
