import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildPerformerRow, createPerformerBackup, deserializePerformerFromServer, migrateLocalPerformers, missingLocalPerformers, normalizePerformerRows, PERFORMER_PRE_SERVER_BACKUP_KEY, shouldOfferPerformerMigration } from "../src/performerServer.js";
import { PERFORMER_LIBRARY_KEY } from "../src/performerLibrary.js";

const performer = (id = "client-a") => ({ id, firstName: "Анна", defaultRate: "1250", unknown: { legacy: true } });
const memoryStorage = (initial = {}) => { const values = new Map(Object.entries(initial)); return { getItem: (key) => values.has(key) ? values.get(key) : null, setItem: (key, value) => values.set(key, value), values }; };

test("Performer serializes without mutation and keeps unknown fields", () => { const input = performer(); const before = structuredClone(input); const row = buildPerformerRow("user-1", input); assert.deepEqual(input, before); assert.equal(row.user_id, "user-1"); assert.equal(row.client_id, "client-a"); assert.deepEqual(row.performer_data.unknown, { legacy: true }); });
test("server row restores client_id as performer.id and normalizes damaged data", () => { const result = deserializePerformerFromServer({ client_id: "server-id", performer_data: "broken" }); assert.equal(result.id, "server-id"); assert.deepEqual(result.additionalRoles, []); });
test("server row client_id overrides stale payload id", () => assert.equal(deserializePerformerFromServer({ client_id: "right", performer_data: { id: "wrong" } }).id, "right"));
test("rows belonging to another user never enter runtime", () => assert.deepEqual(normalizePerformerRows([{ user_id: "u2", client_id: "x", performer_data: {} }], "u1"), []));
test("same names remain separate and name is never an identifier", () => { const rows = [buildPerformerRow("u", performer("one")), buildPerformerRow("u", performer("two"))]; assert.deepEqual(rows.map((row) => row.client_id), ["one", "two"]); });
test("migration offer detects only missing client ids", () => { assert.equal(shouldOfferPerformerMigration([], [performer()]), true); assert.equal(shouldOfferPerformerMigration([], []), false); assert.deepEqual(missingLocalPerformers([performer("same"), performer("new")], [performer("same")]).map((p) => p.id), ["new"]); });
test("backup is made once before migration and localStorage remains", async () => { const storage = memoryStorage({ [PERFORMER_LIBRARY_KEY]: "original" }); const calls = []; const repository = { upsertPerformer: async (userId, item) => { calls.push([userId, item.id]); return item; } }; await migrateLocalPerformers({ userId: "u", performers: [performer("a"), performer("b")], repository, storage }); assert.deepEqual(calls, [["u", "a"], ["u", "b"]]); assert.equal(storage.getItem(PERFORMER_PRE_SERVER_BACKUP_KEY), "original"); storage.setItem(PERFORMER_LIBRARY_KEY, "changed"); assert.equal(createPerformerBackup(storage), false); assert.equal(storage.getItem(PERFORMER_PRE_SERVER_BACKUP_KEY), "original"); });
test("partial migration error is not success", async () => { const repository = { upsertPerformer: async (_u, item) => { if (item.id === "bad") throw new Error("network"); return item; } }; await assert.rejects(() => migrateLocalPerformers({ userId: "u", performers: [performer("ok"), performer("bad")], repository, storage: memoryStorage() }), (error) => error.results.filter((x) => !x.ok).length === 1); });
test("repository is owner scoped, upserts by client id and has no service role", () => { const source = readFileSync(new URL("../src/repositories/performerRepository.js", import.meta.url), "utf8"); assert.match(source, /onConflict: "user_id,client_id"/); assert.match(source, /\.eq\("user_id", userId\)/); assert.doesNotMatch(source, /service_role|secret/i); });
test("migration contains four owner RLS policies", () => { const sql = readFileSync(new URL("../supabase/migrations/20260804020000_create_performers.sql", import.meta.url), "utf8"); for (const operation of ["select", "insert", "update", "delete"]) assert.match(sql, new RegExp(`for ${operation}`)); assert.match(sql, /auth\.uid\(\)/); });
