import test from "node:test";
import assert from "node:assert/strict";
import { addQuickAccessItem, applyQuickAccessPreference, loadQuickAccessState, migrateLegacyQuickAccess, normalizeQuickAccessItem, normalizeQuickAccessState, pinQuickAccessItem, removeQuickAccessItem, sortQuickAccessItems, unpinQuickAccessItem } from "../src/quickAccess.js";

const item = (id, performerId, pinned = false, order = 0) => ({ id, performerId, pinned, order, createdAt: "2026-01-01T00:00:00.000Z" });
test("QuickAccessItem содержит только ссылку, pin, order и дату", () => assert.deepEqual(normalizeQuickAccessItem(item("q", "p")), item("q", "p")));
test("checkbox включён создаёт item, выключен не создаёт", () => { assert.equal(applyQuickAccessPreference({}, "p", true).items.length, 1); assert.equal(applyQuickAccessPreference({}, "p", false).items.length, 0); });
test("два Performer с одинаковым именем допустимы через разные performerId", () => { let state = addQuickAccessItem({}, item("a", "p1")); state = addQuickAccessItem(state, item("b", "p2")); assert.equal(state.items.length, 2); });
test("новый unpinned первый после pinned", () => { let state = normalizeQuickAccessState({ items: [item("p", "1", true), item("old", "2")] }); state = addQuickAccessItem(state, item("new", "3")); assert.deepEqual(sortQuickAccessItems(state).map((x) => x.id), ["p", "new", "old"]); });
test("pinned сверху, pin не создаёт копию и добавляет в конец pinned", () => { let state = { items: [item("p1", "1", true, 0), item("u", "2", false, 0), item("p2", "3", true, 1)] }; state = pinQuickAccessItem(state, "u"); assert.deepEqual(sortQuickAccessItems(state).map((x) => x.id), ["p1", "p2", "u"]); assert.equal(state.items.length, 3); });
test("unpin и delete не затрагивают Performer", () => { const performer = { id: "p", firstName: "Иван" }; let state = unpinQuickAccessItem({ items: [item("q", "p", true)] }, "q"); assert.equal(state.items[0].pinned, false); state = removeQuickAccessItem(state, "q"); assert.equal(state.items.length, 0); assert.deepEqual(performer, { id: "p", firstName: "Иван" }); });
test("количество items не ограничивается", () => { let state = {}; for (let i = 0; i < 150; i++) state = addQuickAccessItem(state, item(`q${i}`, `p${i}`)); assert.equal(state.items.length, 150); });
test("активный формат не содержит history или recentByProject", () => { const state = normalizeQuickAccessState({ recentByProject: { p: [item("x", "p")] } }); assert.deepEqual(state, { items: [] }); assert.equal("recentByProject" in state, false); });
test("повреждённое хранилище загружается безопасно", () => assert.deepEqual(loadQuickAccessState({ getItem: () => "{" }), { items: [] }));
test("миграция сохраняет pinned и связанные explicit items, но не automatic history", () => { const values = { kubiki_quick_access_v1: JSON.stringify({ pinned: [item("pin", "p1", true)], recentByProject: { project: [item("history", "p2")] }, items: [item("linked", "p3")] }) }; const storage = { getItem: (key) => values[key] ?? null, setItem: (key, value) => { values[key] = value; } }; const state = migrateLegacyQuickAccess({}, storage); assert.deepEqual(sortQuickAccessItems(state).map((x) => x.id), ["pin", "linked"]); assert.ok(values.kubiki_quick_access_v1); });
test("повторная миграция не создаёт дубликаты legacy items", () => { const values = { kubiki_quick_access_v1: JSON.stringify({ pinned: [item("pin", "p", true)] }) }; const storage = { getItem: (key) => values[key] ?? null, setItem: (key, value) => { values[key] = value; } }; let state = migrateLegacyQuickAccess({}, storage); state = migrateLegacyQuickAccess(state, storage); assert.equal(state.items.length, 1); });
