import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildQuickAccessRow, createQuickAccessBackup, deserializeQuickAccessItemFromServer, migrateLocalQuickAccess, missingLocalQuickAccessItems, normalizeQuickAccessServerRows, QUICK_ACCESS_PRE_SERVER_BACKUP_KEY } from "../src/quickAccessServer.js";
import { QUICK_ACCESS_KEY } from "../src/quickAccess.js";

const item = (id = "q1", performerId = "p1") => ({ id, performerId, pinned: true, order: 4, createdAt: "2026-01-01T00:00:00.000Z", legacy: { kept: true } });
const memoryStorage = (initial = {}) => { const values = new Map(Object.entries(initial)); return { getItem: (key) => values.has(key) ? values.get(key) : null, setItem: (key, value) => values.set(key, value), values }; };

test("QuickAccessItem serializes without mutation and without sensitive/global data", () => { const input = { ...item(), session: { token: "x" }, env: { secret: true }, project: { id: "project" } }, before = structuredClone(input), row = buildQuickAccessRow("u1", input); assert.deepEqual(input, before); assert.deepEqual(row, { user_id: "u1", client_id: "q1", performer_client_id: "p1", pinned: true, sort_order: 4, item_data: { createdAt: input.createdAt, legacy: { kept: true } } }); assert.equal("performer" in row.item_data, false); });
test("server row restores ids, pinned, order and unknown fields", () => { const result = deserializeQuickAccessItemFromServer({ client_id: "client", performer_client_id: "performer", pinned: true, sort_order: 9, item_data: { createdAt: "2026-01-01T00:00:00.000Z", future: 1 } }); assert.equal(result.id, "client"); assert.equal(result.performerId, "performer"); assert.equal(result.pinned, true); assert.equal(result.order, 9); assert.equal(result.future, 1); });
test("damaged rows and foreign users do not break hydration", () => { assert.deepEqual(normalizeQuickAccessServerRows([{ user_id: "other", client_id: "x" }, { user_id: "u", client_id: "broken", performer_client_id: "" }], "u", ["p"]), { items: [] }); });
test("one performer is normalized to one item while different performer ids remain", () => { const rows = [{ user_id: "u", client_id: "a", performer_client_id: "p", item_data: {} }, { user_id: "u", client_id: "b", performer_client_id: "p", item_data: {} }, { user_id: "u", client_id: "c", performer_client_id: "other", item_data: {} }]; assert.deepEqual(normalizeQuickAccessServerRows(rows, "u", ["p", "other"]).items.map((entry) => entry.id), ["a", "c"]); });
test("migration diff keeps server primary and skips missing Performer links", () => { const result = missingLocalQuickAccessItems({ items: [item("same", "p1"), item("new", "p2"), item("bad", "missing")] }, { items: [item("server", "p1")] }, ["p1", "p2"]); assert.deepEqual(result.items.map((entry) => entry.id), ["new"]); assert.deepEqual(result.skipped.map((entry) => entry.id), ["bad"]); });
test("backup is created once before migration and localStorage remains", async () => { const storage = memoryStorage({ [QUICK_ACCESS_KEY]: "original" }), calls = []; const repository = { upsertQuickAccessItem: async (userId, value) => { calls.push([userId, value.id, value.pinned, value.order]); return value; } }; await migrateLocalQuickAccess({ userId: "u", items: [item()], performerIds: ["p1"], repository, storage }); assert.deepEqual(calls, [["u", "q1", true, 4]]); assert.equal(storage.getItem(QUICK_ACCESS_PRE_SERVER_BACKUP_KEY), "original"); storage.setItem(QUICK_ACCESS_KEY, "changed"); assert.equal(createQuickAccessBackup(storage), false); assert.equal(storage.getItem(QUICK_ACCESS_PRE_SERVER_BACKUP_KEY), "original"); });
test("broken Performer reference is reported and not upserted", async () => { let calls = 0; const results = await migrateLocalQuickAccess({ userId: "u", items: [item("bad", "missing")], performerIds: [], repository: { upsertQuickAccessItem: async () => { calls++; } }, storage: memoryStorage() }); assert.equal(calls, 0); assert.equal(results[0].skipped, true); });
test("partial server error is not migration success", async () => { const repository = { upsertQuickAccessItem: async (_u, value) => { if (value.id === "bad") throw new Error("network"); return value; } }; await assert.rejects(() => migrateLocalQuickAccess({ userId: "u", items: [item("ok", "p1"), item("bad", "p2")], performerIds: ["p1", "p2"], repository, storage: memoryStorage() }), (error) => error.results.filter((entry) => !entry.ok).length === 1); });
test("repository is owner scoped and never uses service role", () => { const source = readFileSync(new URL("../src/repositories/quickAccessRepository.js", import.meta.url), "utf8"); assert.match(source, /onConflict: "user_id,performer_client_id"/); assert.match(source, /\.eq\("user_id", userId\)/); assert.doesNotMatch(source, /service_role|secret/i); });
test("migration has same-user FK, cascade, RLS CRUD and no Project changes", () => { const sql = readFileSync(new URL("../supabase/migrations/20260804030000_create_quick_access_items.sql", import.meta.url), "utf8"); assert.match(sql, /foreign key \(user_id, performer_client_id\)[\s\S]*performers \(user_id, client_id\)[\s\S]*on delete cascade/); for (const op of ["select", "insert", "update", "delete"]) assert.match(sql, new RegExp(`for ${op}`)); assert.match(sql, /auth\.uid\(\)/); });
